# Enable C support
language: c

# Compiler selection
compiler:
  - clang

# Install dependencies
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ninja-build

# Build
script:
  - ninja -f ./build-scripts/nix.ninja

# Run tests
after_success:
  - ./bin/warp-spec-tests.exe ./spec/
